spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
          - id: user-service
            uri: http://localhost:8080
            predicates:
              - Path=/api/v1/users/**
          - id: auth-service
            uri: http://localhost:8080
            predicates:
              - Path=/api/v1/auth/**
          - id: restaurant-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/products/**

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
authentication:
  client:
    base-url: "http://localhost:8080"
    name: "authentication-api-client"
