spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: http://localhost:8080
            predicates:
              - Path=/api/v1/users/**
              - Path=/api/v1/auth/**
server:
  port: 8081
