version: '3.1'

services:
  food-express:
     image: postgres
     restart: always
     container_name: "food-express"
     ports:
        - "5433:5432"
     environment:
       POSTGRES_PASSWORD: secret
       POSTGRES_USER: secret
       POSTGRES_DB: food-express
  redis:
     image: redis
     ports:
       - "6379:6379"