
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/restaurant-express
    username: secret
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: restaurant-service
server:
  port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
